server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-witch-eureka: false
    fetch-register: false
    healthcheck:
      enabled: true
      service-url:
        default-zone: http://localhost:8761/eureka
  instance:
    prefer-id-address: true